#!/usr/bin/env python

# 
# Copyright (c) 2017-Present Pivotal Software, Inc. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import division
import os, re, json, base64
from flask import (Flask, request, jsonify)
from pcfgcp import PcfGcp
from google.cloud import language
from google.cloud import vision

DEBUG = True
LABEL_FRACTION = 0.3 # Min. fraction of image labels in labelSet to trigger an offer TODO: Make tunable
IMAGE_RESIZER_APP = 'image-resizing-service'
app = Flask(__name__)
port = int(os.getenv("PORT", 18080))
pg = PcfGcp()

# Set of top 250 terms found in the item descriptions, generated by running
# ./scripts/generate_product_word_list.py https://storage.googleapis.com/retail-image/toc.txt
# These are all lower case
termSet = set(['dress', 'black', 'lipsy', 'navy', 'shirt', 'jacket', 'blue',
  'lace', 'skirt', 'floral', 'top', 'grey', 'print', 'jeans', 'skinny', 'sleeve',
  'white', 'stripe', 'bodycon', 'hoody', 'trousers', 'blouse', 'denim',
  'embroidered', 'jean', 'adidas', 'zip', 'maxi', 'neck', 'pink', 'boohoo',
  'shoulder', 'maternity', 'ruffle', 'detail', 'nike', 'tie', 'midi', 'printed',
  'wrap', 'eight', 'phase', 'superdry', 'love', 'long', 'sweat', 'coast', 'coat',
  'high', 'keegan', 'michelle', 'french', 'velvet', 'warehouse', 'bardot',
  'dark', 'front', 'joules', 'khaki', 'red', 'wright', 'glamorous', 'jessica',
  'leggings', 'skater', 'cold', 'mid', 'wash', 'connection', 'curve', 'hem',
  'fashion', 'pant', 'short', 'union', 'pleated', 'frill', 'face', 'mint',
  'mini', 'shift', 'cotton', 'jigsaw', 'full', 'legging', 'boden', 'green',
  'leg', 'multi', 'parka', 'shorts', 'karen', 'millen', 'originals',
  'prettylittlething', 'whistles', 'ivory', 'oasis', 'waist', 'orange', 'pencil',
  'slim', 'crew', 'hobbs', 'mango', 'super', 'the', 'trouser', 'wide',
  'jacquard', 'petite', 'belted', 'sequin', 'tight', 'blazer', 'joggers',
  'linen', 'yumi', 'cream', 'leather', 'mistress', 'satin', 'abercrombie',
  'baker', 'fitch', 'little', 'logo', 'armani', 'biker', 'essential', 'mesh',
  'soft', 'ted', 'fat', 'ink', 'levi', 'capri', 'check', 'gym', 'light',
  'textured', 'fleece', 'charcoal', 'knit', 'bomber', 'tunic', 'blush',
  'converse', 'jersey', 'side', 'sweater', 'through', 'vintage', 'jack', 'lost',
  'sweatshirt', 'ecru', 'jogger', 'new', 'armour', 'cropped', 'cut', 'hilfiger',
  'plus', 'prom', 'blend', 'faux', 'over', 'pocket', 'under', 'forever', 'joe',
  'quiz', 'trench', 'trim', 'barbour', 'crop', 'relaxed', 'tee', 'track',
  'wills', 'fur', 'hollister', 'london', 'marl', 'naf', 'off', 'ponte', 'spot',
  'berry', 'boss', 'may', 'noisy', 'panel', 'paper', 'ripped', 'utility',
  'waterproof', 'indigo', 'morgan', 'oversized', 'regatta', 'rise', 'taper',
  'and', 'button', 'cami', 'couture', 'jumper', 'length', 'miss', 'padded',
  'ruched', 'technical', 'vila', 'all', 'ankle', 'browns', 'chino', 'contrast',
  'film', 'girls', 'graphic', 'mela', 'pleat', 'quilted', 'tommy', 'yellow',
  'comino', 'embroidery', 'line', 'overhead', 'rose', 'running', 'selfridge',
  'straight', 'striped', 'tailored', 'with', 'boot', 'collar', 'dolls', 'fit',
  'metallic', 'north', 'peplum', 'vip', 'anita', 'choker', 'flare'])

# Set of labels corresponding with items within our retailer's inventory
# This set was created using ./scripts/generate_labels_for_images.py
# These are all lower case, so use lower() when testing against this set
labelSet = set(['abdomen', 'active pants', 'active shorts', 'active undergarment',
  'arm', 'art', 'bag', 'beige', 'black', 'blazer', 'blond', 
  'blouse', 'blue', 'boardsport', 'boot', 'brand', 'bridal clothing',
  'bridal party dress', 'bridesmaid', 'briefs', 'brown', 'brown hair', 'cardigan', 
  'chair', 'chest', 'child', 'clothing', 'coat', 'cocktail dress', 'collar',
  'costume', 'day dress', 'denim', 'design', 'dress', 'dress shirt', 'electric blue',
  'extreme sport', 'fashion', 'fashion accessory', 'fashion design',
  'finger', 'footwear', 'formal wear', 'fur', 'fur clothing', 'furniture',
  'gentleman', 'glasses', 'gown', 'green', 'hair', 'hairstyle', 'hand',
  'handbag', 'high heeled footwear', 'hood', 'hoodie', 'human action', 'human body',
  'human positions', 'interaction', 'jacket', 'jeans', 'jogging', 'khaki',
  'knitting', 'lace', 'leather', 'leather jacket', 'leg', 'leggings', 'leisure',
  'lingerie', 'lingerie top', 'little black dress', 'long hair', 'magenta',
  'maroon', 'material', 'miniskirt', 'model', 'muscle', 'neck', 'one piece swimsuit',
  'outerwear', 'overcoat', 'paisley', 'pattern', 'peach', 'person',
  'photo shoot', 'physical exercise', 'physical fitness', 'pink', 'plaid',
  'pocket', 'polar fleece', 'polka dot', 'product', 'prom', 'purple', 'red',
  'running', 'satin', 'shirt', 'shoe', 'shorts', 'sitting', 'skort', 'sleeve',
  'sneakers', 'spandex', 'sport venue', 'sports', 'sports uniform', 'sportswear',
  'spring', 'strength training', 'suit', 'supermodel', 'sweater', 'sweatshirt',
  'swim brief', 'swimsuit top', 'swimwear', 't shirt', 'tartan', 'textile',
  'thigh', 'tights', 'trench coat', 'trousers', 'trunk', 'trunks', 'tuxedo',
  'underpants', 'wedding dress', 'white', 'woman', 'wool', 'yellow', 'zipper'])

def logMsg(args):
    print "[Instance: %s] %s" % (str(os.getenv("CF_INSTANCE_INDEX", 0)), args)

"""Returns a URL which will run the image through the image resizing app to ensure
it fits into the bounds suggested by the GCP Vision API, for label detection.

The return value here should be passed into the Vision API as the `source_uri`
(see below)

Requires this app to be bound to a user provided service pointing to the resizing
app (https://github.com/cf-platform-eng/image-resizing-service)
"""
imgSize = 640
imgResizerUrl = None
def getResizedImageUrl(origUrl):
  global imgResizerUrl
  if imgResizerUrl is None:
    vcapApp = json.loads(os.getenv('VCAP_APPLICATION'))
    thisHost = vcapApp['application_uris'][0]
    imgHost = re.sub(r'^[^\.]+', IMAGE_RESIZER_APP, thisHost)
    imgResizerUrl = 'http://' + imgHost + '/'
  # Format => http://localhost:18080/?size=256&urlBase64=aHR0cDoL3...QmlcGc=
  rv = '{}?size={}&urlBase64={}'.format(imgResizerUrl, imgSize, base64.b64encode(origUrl))
  logMsg('Resize image URL: %s' % rv)
  return rv

"""Detects labels in the file located in Google Cloud Storage or on the Web.
  Ref. https://googlecloudplatform.github.io/google-cloud-python/stable/vision-usage.html

  Example:
  labels = image.detect_labels(limit=3)
  labels[0].description # => 'automobile'
  labels[0].score => 0.9863683

  Returns: List of label values
"""
def detectLabelsUri(uri):
  client = pg.getVision()
  image = client.image(source_uri=getResizedImageUrl(uri))
  labels = []
  for label in image.detect_labels():
    labels.append(label.description.lower()) # lower() to match labelSet
  return labels

def getMessageText(msg):
  return msg['text'] # For Twitter

# FIXME: Factor out all Twitter specific parts into the "twitter" module
@app.route('/', methods = ['POST', 'GET'])
def jsonHandler():
  obj = request.get_json(force=True)
  makeOffer = False
  msgText = getMessageText(obj)

  # Analyze document using GCP ML Language API
  # Any sentiment value > 0 triggers offer
  lang = pg.getLanguage()
  doc = lang.document_from_text(msgText)
  annotations = doc.annotate_text(include_sentiment=True, include_syntax=False, include_entities=False)
  obj['sentiment'] = {
    'score': annotations.sentiment.score,
    'magnitude': annotations.sentiment.magnitude
  }
  if annotations.sentiment.score > 0.0:
    makeOffer = True

  # Here, if the message contains references to images, check the image labels;
  # if there are no images, then analyze the message itself against the set of
  # terms relevent to our inventory.
  relevantLabels = []
  if makeOffer and 'entities' in obj and 'media' in obj['entities']:
    # Handle any image references using GCP ML Vision API
    labelScore = 0
    numLabels = 0
    for mediaItem in obj['entities']['media']:
      imgUrl = mediaItem['media_url']
      logMsg('Image URL: %s' % imgUrl)
      labels = detectLabelsUri(imgUrl)
      numLabels += len(labels)
      for label in labels:
        if label in labelSet:
          relevantLabels.append(label)
          labelScore += 1
      # Add this label's array as a new attribute
      mediaItem['vision_labels'] = labels
    # Combine sentiment based offer decision with image based one
    makeOffer &= (labelScore / numLabels >= LABEL_FRACTION)
  else:
    # Analyze terms in text to see if they occur in item termSet
    nHits = 0
    for word in re.split(r'[^\w_]+', msgText.lower()):
      if len(word) > 2 and word in termSet:
        nHits += 1
    makeOffer &= (nHits > 0)
    # 27 April 2017: for now, images are required for us to make an offer
    makeOffer = False

  # TODO: More sophisticated analysis of syntax to trigger offer
  # Try a GloVe model of "need", "desire", etc. (https://github.com/maciejkula/glove-python)
  obj['relevant_labels'] = relevantLabels
  obj['make_offer'] = makeOffer
  logMsg(json.dumps(obj, sort_keys=True, indent=2))
  return json.dumps(obj)

@app.route('/status')
def test():
    return "STATUS_OK"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=port, threaded = not DEBUG, debug = DEBUG)

